// <auto-generated />
using System;
using LabLinkBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabLinkBackend.Migrations
{
    [DbContext(typeof(LabLinkDbContext))]
    partial class LabLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabLinkBackend.Models.Accession", b =>
                {
                    b.Property<int>("AccessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessionId"));

                    b.Property<DateTime?>("AccessionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccessionId")
                        .HasName("PK__Accessio__B4B2533D91A55B9E");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "AccessionNumber" }, "UQ__Accessio__AE5A718E0F85B240")
                        .IsUnique();

                    b.ToTable("Accession", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Addendum", b =>
                {
                    b.Property<int>("AddendumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddendumId"));

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddendumText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddendumId")
                        .HasName("PK__Addendum__5F1020D068A42B79");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Addendum", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BookedDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PhlebotomistId")
                        .HasColumnType("int");

                    b.Property<int?>("VisitTypeId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC2B0F9F50F");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhlebotomistId");

                    b.HasIndex("VisitTypeId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.AppointmentItem", b =>
                {
                    b.Property<int>("AppItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppItemId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("PanelId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.HasKey("AppItemId")
                        .HasName("PK__Appointm__2AB731087A1FB9A1");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("AppointmentItem", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F23989F516BA0");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.ClientAccount", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("ClientId")
                        .HasName("PK__ClientAc__E67E1A245BD6D29B");

                    b.ToTable("ClientAccount", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.CompetencyLog", b =>
                {
                    b.Property<int>("CompetencyLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyLogId"));

                    b.Property<string>("CompetencyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("StaffUserId")
                        .HasColumnType("int");

                    b.HasKey("CompetencyLogId")
                        .HasName("PK__Competen__E76A996DF8042AE6");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("CompetencyLog", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.ContainerType", b =>
                {
                    b.Property<int>("ContainerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecimenType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContainerTypeId")
                        .HasName("PK__Containe__46FA6FD9D73872C8");

                    b.ToTable("ContainerType", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED58D910D0");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Flag", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlagId"));

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("FlagId")
                        .HasName("PK__Flags__780D4593B1088662");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InstrumentRef", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"));

                    b.Property<int?>("InterfaceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstrumentId")
                        .HasName("PK__Instrume__430A5386B333FA88");

                    b.HasIndex("InterfaceTypeId");

                    b.ToTable("InstrumentRef", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.InterfaceType", b =>
                {
                    b.Property<int>("InterfaceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterfaceTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterfaceTypeId")
                        .HasName("PK__Interfac__BF5D47AB1A5F52B1");

                    b.ToTable("InterfaceType", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.InvoiceRef", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceId")
                        .HasName("PK__InvoiceR__D796AAB55F37DD7D");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PatientId");

                    b.ToTable("InvoiceRef", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrderedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__LabOrder__C3905BCFE8228F02");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderedByUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("LabOrder", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("AuthorizedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AuthorizedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GeneratedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ReportUri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReportURI");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ReportId")
                        .HasName("PK__LabRepor__D5BD4805FD806413");

                    b.HasIndex("AuthorizedBy");

                    b.HasIndex("OrderId");

                    b.ToTable("LabReport", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabReportPack", b =>
                {
                    b.Property<int>("LabReportPackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabReportPackId"));

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LabReportPackId")
                        .HasName("PK__LabRepor__6A46AD253081057A");

                    b.ToTable("LabReportPack", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12915FB6C3");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PanelId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__57ED0681F61DDCD8");

                    b.HasIndex("OrderId");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Panel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PanelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PanelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PanelId")
                        .HasName("PK__Panel__49CA68064C2DDDA0");

                    b.HasIndex(new[] { "PanelCode" }, "UQ__Panel__75B0AFB7AC7DF449")
                        .IsUnique();

                    b.ToTable("Panel", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.PanelTest", b =>
                {
                    b.Property<int>("PanelTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelTestId"));

                    b.Property<string>("ComponentsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ComponentsJSON");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PanelId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("PanelTestId")
                        .HasName("PK__PanelTes__E1CE350B09B50239");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("PanelTest", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.PathologyReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Patholog__74BC79CE155427F1");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("PathologyReview", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrimaryPhysicianId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC36608EDAFF3");

                    b.HasIndex("PrimaryPhysicianId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Patient__1788CC4D85CB9787")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentModeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PaymentModeId")
                        .HasName("PK__PaymentM__F95995495A034130");

                    b.ToTable("PaymentMode", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.PaymentRef", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.HasKey("PaymentId")
                        .HasName("PK__PaymentR__9B556A38E358416C");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModeId");

                    b.ToTable("PaymentRef", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.PriceRef", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("PanelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.HasKey("PriceId")
                        .HasName("PK__PriceRef__49575BAFCCA63FBE");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("PriceRef", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Qcrecord", b =>
                {
                    b.Property<int>("QcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QcId"));

                    b.Property<string>("ControlLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("ResultValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RuleFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RunDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Units")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QcId")
                        .HasName("PK__QCRecord__F5ECB18C1371668F");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TestId");

                    b.ToTable("QCRecord", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipientId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("RecipientRefId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("RecipientId")
                        .HasName("PK__Recipien__F0A6024D9FC08155");

                    b.HasIndex("ReportId");

                    b.ToTable("Recipient", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.ReportDelivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId")
                        .HasName("PK__ReportDe__626D8FCE67F33EC6");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportDelivery", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.ResultEntry", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("Analyte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EnteredBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnteredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FlagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Units")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ResultId")
                        .HasName("PK__ResultEn__976902088E748652");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("FlagId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("TestId");

                    b.ToTable("ResultEntry", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A917EB82E");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Speciman", b =>
                {
                    b.Property<int>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecimenId"));

                    b.Property<int?>("CollectedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CollectedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecimenTypeId")
                        .HasColumnType("int");

                    b.HasKey("SpecimenId")
                        .HasName("PK__Specimen__719B2271ECD3FE50");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("SpecimenTypeId");

                    b.ToTable("Specimen");
                });

            modelBuilder.Entity("LabLinkBackend.Models.SpecimenType", b =>
                {
                    b.Property<int>("SpecimenTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecimenTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecimenTypeId")
                        .HasName("PK__Specimen__0218E7DB1A433393");

                    b.ToTable("SpecimenType", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.TechValidation", b =>
                {
                    b.Property<int>("TvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TvId"));

                    b.Property<string>("DeltaCheckJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeltaCheckJSON");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("TvId")
                        .HasName("PK__TechVali__F97248AE2536D887");

                    b.HasIndex("ResultId");

                    b.HasIndex("UserId");

                    b.ToTable("TechValidation", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxNormalValue")
                        .HasColumnType("int");

                    b.Property<int?>("MethodId")
                        .HasColumnType("int");

                    b.Property<int>("MinNormalValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefRangeJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RefRangeJSON");

                    b.Property<int?>("SpecimenTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TattargetMinutes")
                        .HasColumnType("int")
                        .HasColumnName("TATTargetMinutes");

                    b.Property<int?>("Units")
                        .HasColumnType("int");

                    b.Property<double?>("VolumeReq")
                        .HasColumnType("float");

                    b.HasKey("TestId")
                        .HasName("PK__Test__8CC33160062D6592");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecimenTypeId");

                    b.HasIndex(new[] { "Code" }, "UQ__Test__A25C5AA711F98565")
                        .IsUnique();

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C1BF5332B");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105349E858773")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Assigned_At");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId")
                        .HasName("PK__UserRole__3D978A3546C5285A");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Visit", b =>
                {
                    b.Property<int>("VisitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VisitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VisitTypeId")
                        .HasName("PK__Visit__9BF3CC522C1C3095");

                    b.ToTable("Visit", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Worklist", b =>
                {
                    b.Property<int>("WorklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorklistId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorklistId")
                        .HasName("PK__Worklist__F44B6698671EB079");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Worklist", (string)null);
                });

            modelBuilder.Entity("LabLinkBackend.Models.Accession", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("Accessions")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Accession_Order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Addendum", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("Addenda")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Addendum_Order");

                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("Addenda")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Addendum_User");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Appointment", b =>
                {
                    b.HasOne("LabLinkBackend.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.HasOne("LabLinkBackend.Models.User", "Phlebotomist")
                        .WithMany("Appointments")
                        .HasForeignKey("PhlebotomistId")
                        .HasConstraintName("FK_Appointment_User");

                    b.HasOne("LabLinkBackend.Models.Visit", "VisitType")
                        .WithMany("Appointments")
                        .HasForeignKey("VisitTypeId")
                        .HasConstraintName("FK_Appointment_Visit");

                    b.Navigation("Patient");

                    b.Navigation("Phlebotomist");

                    b.Navigation("VisitType");
                });

            modelBuilder.Entity("LabLinkBackend.Models.AppointmentItem", b =>
                {
                    b.HasOne("LabLinkBackend.Models.Appointment", "Appointment")
                        .WithMany("AppointmentItems")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AppItem_Appointment");

                    b.HasOne("LabLinkBackend.Models.Panel", "Panel")
                        .WithMany("AppointmentItems")
                        .HasForeignKey("PanelId")
                        .HasConstraintName("FK_AppItem_Panel");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("AppointmentItems")
                        .HasForeignKey("TestId")
                        .HasConstraintName("FK_AppItem_Test");

                    b.Navigation("Appointment");

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.AuditLog", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.CompetencyLog", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "Reviewer")
                        .WithMany("CompetencyLogReviewers")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_CompetencyLog_Reviewer");

                    b.HasOne("LabLinkBackend.Models.User", "StaffUser")
                        .WithMany("CompetencyLogStaffUsers")
                        .HasForeignKey("StaffUserId")
                        .IsRequired()
                        .HasConstraintName("FK_CompetencyLog_Staff");

                    b.Navigation("Reviewer");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InstrumentRef", b =>
                {
                    b.HasOne("LabLinkBackend.Models.InterfaceType", "InterfaceType")
                        .WithMany("InstrumentRefs")
                        .HasForeignKey("InterfaceTypeId")
                        .HasConstraintName("FK_Instrument_Interface");

                    b.Navigation("InterfaceType");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InvoiceRef", b =>
                {
                    b.HasOne("LabLinkBackend.Models.ClientAccount", "Client")
                        .WithMany("InvoiceRefs")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_Invoice_Client");

                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("InvoiceRefs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Order");

                    b.HasOne("LabLinkBackend.Models.Patient", "Patient")
                        .WithMany("InvoiceRefs")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Patient");

                    b.Navigation("Client");

                    b.Navigation("Order");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabOrder", b =>
                {
                    b.HasOne("LabLinkBackend.Models.ClientAccount", "Client")
                        .WithMany("LabOrders")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_LabOrder_Client");

                    b.HasOne("LabLinkBackend.Models.User", "OrderedByUser")
                        .WithMany("LabOrders")
                        .HasForeignKey("OrderedByUserId")
                        .HasConstraintName("FK_LabOrder_User");

                    b.HasOne("LabLinkBackend.Models.Patient", "Patient")
                        .WithMany("LabOrders")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_LabOrder_Patient");

                    b.Navigation("Client");

                    b.Navigation("OrderedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabReport", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "AuthorizedByNavigation")
                        .WithMany("LabReports")
                        .HasForeignKey("AuthorizedBy")
                        .HasConstraintName("FK_LabReport_User");

                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("LabReports")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_LabReport_Order");

                    b.Navigation("AuthorizedByNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Notification", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.OrderItem", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("LabLinkBackend.Models.Panel", "Panel")
                        .WithMany("OrderItems")
                        .HasForeignKey("PanelId")
                        .HasConstraintName("FK_OrderItem_Panel");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("OrderItems")
                        .HasForeignKey("TestId")
                        .HasConstraintName("FK_OrderItem_Test");

                    b.Navigation("Order");

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.PanelTest", b =>
                {
                    b.HasOne("LabLinkBackend.Models.Panel", "Panel")
                        .WithMany("PanelTests")
                        .HasForeignKey("PanelId")
                        .IsRequired()
                        .HasConstraintName("FK_PanelTest_Panel");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("PanelTests")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_PanelTest_Test");

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.PathologyReview", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("PathologyReviews")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_PathologyReview_Order");

                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("PathologyReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PathologyReview_User");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Patient", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "PrimaryPhysician")
                        .WithMany("PatientPrimaryPhysicians")
                        .HasForeignKey("PrimaryPhysicianId")
                        .HasConstraintName("FK_Patient_Physician");

                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithOne("PatientUser")
                        .HasForeignKey("LabLinkBackend.Models.Patient", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_User");

                    b.Navigation("PrimaryPhysician");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.PaymentRef", b =>
                {
                    b.HasOne("LabLinkBackend.Models.InvoiceRef", "Invoice")
                        .WithMany("PaymentRefs")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Invoice");

                    b.HasOne("LabLinkBackend.Models.PaymentMode", "Mode")
                        .WithMany("PaymentRefs")
                        .HasForeignKey("ModeId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Mode");

                    b.Navigation("Invoice");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("LabLinkBackend.Models.PriceRef", b =>
                {
                    b.HasOne("LabLinkBackend.Models.Panel", "Panel")
                        .WithMany("PriceRefs")
                        .HasForeignKey("PanelId")
                        .HasConstraintName("FK_PriceRef_Panel");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("PriceRefs")
                        .HasForeignKey("TestId")
                        .HasConstraintName("FK_PriceRef_Test");

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Qcrecord", b =>
                {
                    b.HasOne("LabLinkBackend.Models.InstrumentRef", "Instrument")
                        .WithMany("Qcrecords")
                        .HasForeignKey("InstrumentId")
                        .IsRequired()
                        .HasConstraintName("FK_QCRecord_Instrument");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("Qcrecords")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_QCRecord_Test");

                    b.Navigation("Instrument");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Recipient", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabReport", "Report")
                        .WithMany("Recipients")
                        .HasForeignKey("ReportId")
                        .IsRequired()
                        .HasConstraintName("FK_Recipient_Report");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("LabLinkBackend.Models.ReportDelivery", b =>
                {
                    b.HasOne("LabLinkBackend.Models.LabReport", "Report")
                        .WithMany("ReportDeliveries")
                        .HasForeignKey("ReportId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportDelivery_Report");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("LabLinkBackend.Models.ResultEntry", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "EnteredByNavigation")
                        .WithMany("ResultEntries")
                        .HasForeignKey("EnteredBy")
                        .HasConstraintName("FK_ResultEntry_User");

                    b.HasOne("LabLinkBackend.Models.Flag", "Flag")
                        .WithMany("ResultEntries")
                        .HasForeignKey("FlagId")
                        .IsRequired()
                        .HasConstraintName("FK_ResultEntry_Flag");

                    b.HasOne("LabLinkBackend.Models.OrderItem", "OrderItem")
                        .WithMany("ResultEntries")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ResultEntry_OrderItem");

                    b.HasOne("LabLinkBackend.Models.Test", "Test")
                        .WithMany("ResultEntries")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_ResultEntry_Test");

                    b.Navigation("EnteredByNavigation");

                    b.Navigation("Flag");

                    b.Navigation("OrderItem");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Speciman", b =>
                {
                    b.HasOne("LabLinkBackend.Models.User", "CollectedByNavigation")
                        .WithMany("Specimen")
                        .HasForeignKey("CollectedBy")
                        .HasConstraintName("FK_Specimen_User");

                    b.HasOne("LabLinkBackend.Models.ContainerType", "ContainerType")
                        .WithMany("Specimen")
                        .HasForeignKey("ContainerTypeId")
                        .HasConstraintName("FK_Specimen_ContainerType");

                    b.HasOne("LabLinkBackend.Models.LabOrder", "Order")
                        .WithMany("Specimen")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Specimen_Order");

                    b.HasOne("LabLinkBackend.Models.OrderItem", "OrderItem")
                        .WithMany("Specimen")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Specimen_OrderItem");

                    b.HasOne("LabLinkBackend.Models.SpecimenType", "SpecimenType")
                        .WithMany("Specimen")
                        .HasForeignKey("SpecimenTypeId")
                        .HasConstraintName("FK_Specimen_SpecimenType");

                    b.Navigation("CollectedByNavigation");

                    b.Navigation("ContainerType");

                    b.Navigation("Order");

                    b.Navigation("OrderItem");

                    b.Navigation("SpecimenType");
                });

            modelBuilder.Entity("LabLinkBackend.Models.TechValidation", b =>
                {
                    b.HasOne("LabLinkBackend.Models.ResultEntry", "Result")
                        .WithMany("TechValidations")
                        .HasForeignKey("ResultId")
                        .IsRequired()
                        .HasConstraintName("FK_TechValidation_Result");

                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("TechValidations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TechValidation_User");

                    b.Navigation("Result");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Test", b =>
                {
                    b.HasOne("LabLinkBackend.Models.ContainerType", "ContainerType")
                        .WithMany("Tests")
                        .HasForeignKey("ContainerTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Test_ContainerType");

                    b.HasOne("LabLinkBackend.Models.Department", "Department")
                        .WithMany("Tests")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Test_Department");

                    b.HasOne("LabLinkBackend.Models.SpecimenType", "SpecimenType")
                        .WithMany("Tests")
                        .HasForeignKey("SpecimenTypeId")
                        .HasConstraintName("FK_Test_SpecimenType");

                    b.Navigation("ContainerType");

                    b.Navigation("Department");

                    b.Navigation("SpecimenType");
                });

            modelBuilder.Entity("LabLinkBackend.Models.UserRole", b =>
                {
                    b.HasOne("LabLinkBackend.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("LabLinkBackend.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Worklist", b =>
                {
                    b.HasOne("LabLinkBackend.Models.InstrumentRef", "Instrument")
                        .WithMany("Worklists")
                        .HasForeignKey("InstrumentId")
                        .HasConstraintName("FK_Worklist_Instrument");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentItems");
                });

            modelBuilder.Entity("LabLinkBackend.Models.ClientAccount", b =>
                {
                    b.Navigation("InvoiceRefs");

                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("LabLinkBackend.Models.ContainerType", b =>
                {
                    b.Navigation("Specimen");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Department", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Flag", b =>
                {
                    b.Navigation("ResultEntries");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InstrumentRef", b =>
                {
                    b.Navigation("Qcrecords");

                    b.Navigation("Worklists");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InterfaceType", b =>
                {
                    b.Navigation("InstrumentRefs");
                });

            modelBuilder.Entity("LabLinkBackend.Models.InvoiceRef", b =>
                {
                    b.Navigation("PaymentRefs");
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabOrder", b =>
                {
                    b.Navigation("Accessions");

                    b.Navigation("Addenda");

                    b.Navigation("InvoiceRefs");

                    b.Navigation("LabReports");

                    b.Navigation("OrderItems");

                    b.Navigation("PathologyReviews");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("LabLinkBackend.Models.LabReport", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("ReportDeliveries");
                });

            modelBuilder.Entity("LabLinkBackend.Models.OrderItem", b =>
                {
                    b.Navigation("ResultEntries");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Panel", b =>
                {
                    b.Navigation("AppointmentItems");

                    b.Navigation("OrderItems");

                    b.Navigation("PanelTests");

                    b.Navigation("PriceRefs");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("InvoiceRefs");

                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("LabLinkBackend.Models.PaymentMode", b =>
                {
                    b.Navigation("PaymentRefs");
                });

            modelBuilder.Entity("LabLinkBackend.Models.ResultEntry", b =>
                {
                    b.Navigation("TechValidations");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LabLinkBackend.Models.SpecimenType", b =>
                {
                    b.Navigation("Specimen");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Test", b =>
                {
                    b.Navigation("AppointmentItems");

                    b.Navigation("OrderItems");

                    b.Navigation("PanelTests");

                    b.Navigation("PriceRefs");

                    b.Navigation("Qcrecords");

                    b.Navigation("ResultEntries");
                });

            modelBuilder.Entity("LabLinkBackend.Models.User", b =>
                {
                    b.Navigation("Addenda");

                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("CompetencyLogReviewers");

                    b.Navigation("CompetencyLogStaffUsers");

                    b.Navigation("LabOrders");

                    b.Navigation("LabReports");

                    b.Navigation("Notifications");

                    b.Navigation("PathologyReviews");

                    b.Navigation("PatientPrimaryPhysicians");

                    b.Navigation("PatientUser");

                    b.Navigation("ResultEntries");

                    b.Navigation("Specimen");

                    b.Navigation("TechValidations");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LabLinkBackend.Models.Visit", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
